version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_personalhierarchie
    ports:
      - "7474:7474" # HTTP port for Neo4j browser
      - "7687:7687" # Bolt port for application connections
    environment:
      - NEO4J_AUTH=neo4j/mysecretpassword
