version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_personalhierarchie
    ports:
      - "7474:7474" # HTTP-Port für Web-UI "Neo4j Browser"
      - "7687:7687" # Bolt-Port für Zugriff über Treiber
    environment:
      - NEO4J_AUTH=neo4j/mysecretpassword
